<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */

$this->headTitle('Reservation');
?>
<div class="card border-success text-center mx-auto mb-3" style="max-width: 26rem;">
    <div class="card-header">Confirmation</div>
    <div class="card-body text-success">
        <h5 class="card-title">Success !</h5>
        <p class="card-text">
            Your reservation has been registered.<br>
            You you will soon receive a confirmation email.
        </p>
    </div>
</div>
