<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
/** @var \App\UI\Reservation\Facade\Assembler\DTO\EventDTO[] $events */

$this->headTitle('Reservation');
?>
<div class="row">
<?php foreach ($events as $event): ?>
    <div class="col-lg-4">
        <div class="card mb-4 shadow-sm">
            <img src="<?= $event->imageURL ?>">
            <div class="card-body">
                <h2><?= $event->name ?></h2>
                <p class="card-text" style="height: 10em;"><?= $event->description ?></p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <form method="post" action="<?= $this->url('reservation.submit', ['step' => 'event']) ?>">
                            <input type="hidden" name="eventSlug" value="<?= $event->slug ?>">
                            <button type="submit" class="btn btn-sm btn-outline-primary">Reserve</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endforeach ?>
</div>
